male(adam).
male(john).
male(mark).
male(joshua).
male(david).
female(eve).
female(helen).
female(ivonne).
female(anna).
parent(adam,helen).
parent(adam,ivonne).
parent(adam,anna).
parent(eve,helen).
parent(eve,ivonne).
parent(eve,anna).
parent(john,joshua).
parent(helen,joshua).
parent(ivonne,david).
parent(mark,david).
sibling(X,Y):-X\=Y,parent(Z,X),parent(Z,Y).
sister(X,Y):-female(X),sibling(X,Y).
grandson(X,Y):-parent(X,Z),parent(Z,Y).
cousin(X,Y):-parent(Z,X),parent(L,Y),sibling(Z,L).
descendant(X,Y):-parent(Y,X);parent(Y,Z),descendant(X,Z).
is_mother(X):-female(X),parent(X,Y).
is_father(X):-male(X),parent(X,Y).
